server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://192.168.0.113:3307/mybatis
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  application:
    name: service-provider
mybatis:
  type-aliases-package: com.myp.service.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

