server:
  port: 10010
spring:
  application:
    name: myp-zuul
zuul:
  routes:
    service-provider: /service-provider/**
    prefix: /api
      # path: /service-provider/**
      #url: http://localhost:8083
      # serviceId: service-provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
