server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
spring:
  application:
    name: service-customer
service-provider:
    ribbon:
      NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000 #色湖之hystrix的超时时间
feign:
  hystrix:
    enabled: true
